# Generated by Django 5.0.6 on 2024-05-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
